# Generated by Django 3.2.8 on 2021-10-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='adminwebsite_adminuser',
        ),
    ]
