# Generated by Django 3.2.8 on 2021-10-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwebsite', '0002_alter_adminuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table=None,
        ),
    ]
